

    const FETCH_CATEGORIES = "FETCH_CATEGORIES";
    const FETCH_CATEGORY_SELECTED = "FETCH_CATEGORY_SELECTED";
    const GET_RECIPE = "GET_RECIPE";
    const GET_QUERY  = "GET_QUERY ";
     
    const ADD_FAV = "ADD_FAV";
    const REMOVE_FAV = "REMOVE_FAV";
 
    
     
    
    export { FETCH_CATEGORIES, FETCH_CATEGORY_SELECTED, GET_RECIPE, GET_QUERY, ADD_FAV, REMOVE_FAV};